# HTTP -> HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name marcosfreitas.dev www.marcosfreitas.dev;
    return 301 https://$host$request_uri;
}

# HTTPS
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name marcosfreitas.dev www.marcosfreitas.dev;

    ssl_certificate     /etc/letsencrypt/live/marcosfreitas.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/marcosfreitas.dev/privkey.pem;

    root /root/marcosfreitas.dev/src/pages;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /styles/ {
        alias /root/marcosfreitas.dev/src/styles/;
    }

    location /scripts/ {
        alias /root/marcosfreitas.dev/src/scripts/;
    }
}
